name: Pest Test Suite

on:
  workflow_dispatch:

jobs:
  pest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Notice
      run: echo "Tests are run locally. This workflow is available for manual dispatch only."
